name: Documentation Tests
on:
  workflow_call:
  workflow_dispatch:  # to trigger manually

permissions:
  contents: read

jobs:
  doctest:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup python environment
        uses: durandtibo/setup-venv-uv-action@v0.0.2

      - name: Run doctest on source code
        run: |
          inv doctest-src

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup python environment
        uses: durandtibo/setup-venv-uv-action@v0.0.2
        with:
          install-args: '--docs-deps'

      - name: Setup doc deploy
        env:
          CI_BOT_EMAIL: ${{secrets.CI_BOT_EMAIL}}
        run: |
          git config --global user.name ci-docs-bot
          git config --global user.email "$CI_BOT_EMAIL"

      - name: Build documentation
        run: |
          mike deploy --config-file docs/mkdocs.yml --branch tmp-doc-build-1234 dev
